"""add day counter

Revision ID: 12aa266eab1f
Revises: c4ecf086b08d
Create Date: 2025-07-20 19:31:02.788635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12aa266eab1f'
down_revision: Union[str, Sequence[str], None] = 'c4ecf086b08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutritional_data', sa.Column('day_counter', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('day_counter', sa.Integer(), nullable=False, server_default='0'))



def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('users', 'day_counter')
    op.drop_column('nutritional_data', 'day_counter')
