AWAITING_FOR_USER_DATA = "AWAITING_FOR_USER_DATA"

AWAITING_FOR_AUDIO_FOOD = "AWAITING_FOR_AUDIO_FOOD"
AWAITING_FOR_TEXT_FOOD = "AWAITING_FOR_TEXT_FOOD"
AWAITING_FOR_PHOTO_FOOD = "AWAITING_FOR_PHOTO_FOOD"

NO_ACTIONS_REQUIRED = "NO_ACTIONS_REQUIRED"

CHAT_STAGES = [
    AWAITING_FOR_USER_DATA,
    AWAITING_FOR_AUDIO_FOOD,
    AWAITING_FOR_TEXT_FOOD,
    AWAITING_FOR_PHOTO_FOOD,
    NO_ACTIONS_REQUIRED,
]

STAGE_TO_TEXT = {
    AWAITING_FOR_USER_DATA: "Скажіть скільки вам років, зріст та вагу (голосове чи текст)",
    AWAITING_FOR_AUDIO_FOOD: "Скажи шо жер, запиши войс",
    AWAITING_FOR_TEXT_FOOD: "Скажи шо жер, напиши текстом",
    AWAITING_FOR_PHOTO_FOOD: "Скинь фотку того шо жер (поки не робе)",
    NO_ACTIONS_REQUIRED: "Маладєц, справився",
}